spring.application.name=kshop-backend

# =========================================================
# DATABASE - PostgreSQL LOCAL
# =========================================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# SSL OBLIGATOIRE (SUPABASE)
# ===============================
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================================================
# SERVER
# =========================================================

server.port=${PORT:8080}

# =========================================================
# JWT
# =========================================================

app.jwt.secret=KShopDevSecretKeyForJwtAuthentication2026VeryLongSecretKey
app.jwt.expiration=86400000